/**
 * Vitest stub for SvelteKit's virtual `$app/navigation` module.
 *
 * The real module is generated by `svelte-kit sync` and only exists at
 * dev/build time. Unit tests run through plain Vite and therefore can't
 * resolve the import, which causes the whole layout test file to fail
 * with "Failed to resolve import" before any vi.mock factory runs.
 *
 * This stub provides the minimum surface used by `+layout.svelte` and
 * any other component that imports from `$app/navigation`. Individual
 * tests can still override with `vi.mock('$app/navigation', () => …)`.
 */
export const afterNavigate = (
  _fn: (nav: { to: { url: URL } | null }) => void,
): void => {
  // no-op in unit tests; navigation is exercised by the e2e suite
};

export const goto = async (_url: string): Promise<void> => {
  // no-op
};

export const beforeNavigate = (_fn: () => void): void => {
  // no-op
};
